export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 style={{ backgroundColor: "yellow", padding: "2rem" }}>header</h1>
        </header>
        {children}
        <footer>
          <h1 style={{ backgroundColor: "aqua", padding: "2rem" }}>Footer</h1>
          <div>
            <div >
              <p>All rights reserved</p>
              <p>2024</p>
            </div>
            <div></div>
          </div>
        </footer>
      </body>
    </html>
  )
}
